---

- name: Python externally managed
  ansible.builtin.import_tasks: python-externally-managed.yml

- name: Ensure Zkg Zeek Package Manager is present
  ansible.builtin.pip:
    name: zkg
    state: present
    executable: "{{ pip_bin | default('pip3') }}"
  register: pkg_result
  until: pkg_result is success
