---

- name: Check zeek
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "{{ broids_broctl }} check"
  become: yes
  become_user: "{{ broids_user }}"

- name: Deploy zeek
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "{{ broids_broctl }} deploy"
  become: yes
  become_user: "{{ broids_user }}"

- name: Restart zeek
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "{{ broids_broctl }} restart"
  become: yes
  become_user: "{{ broids_user }}"

- name: Restart monit
  ansible.builtin.service:
    name: monit
    state: restarted

- name: Fetch critical-stack-intel feeds
  ansible.builtin.command:  # noqa no-changed-when
    cmd: critical-stack-intel pull

- name: Restart apparmor
  ansible.builtin.service:
    name: apparmor
    state: restarted
  when: travisci is defined and travisci
